name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
        architecture: [x64, Win32]

    steps:
      - name: Clone repository to runner
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure with CMake
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A ${{ matrix.architecture }}

      - name: Build the project
        run: cmake --build build --config ${{ matrix.configuration }}